[main]
work_dir = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox"
exp_dir = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp"
raw_config_path = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp/config.toml"
device = "cuda:0"
n_trials = 1

[data]
real_data_dir = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/data"
numerical_feature_column_path = "numerical_feture_columns.csv"
categorical_feature_column_path = "categorical_feature_columns.csv"

[data.y]
num_classes = 2
label_column = "CVDs"

[data.x]
n_numerical_features = 14
n_categorical_features = 10
numerical_feature_columns = [
    "age",
    "height",
    "weight",
    "waist",
    "hip",
    "fpg",
    "fin",
    "tg",
    "tc",
    "hdl",
    "ldl",
    "crp",
    "SBP",
    "DBP",
]
categorical_feature_columns = [
    "sex",
    "htn1",
    "dyl1",
    "ms",
    "IGT",
    "IFG",
    "both_IFG_IGT",
    "PreDM",
    "DM",
    "DM_PreDM",
]
num_classes = [
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
]

[train.T]
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
seed = 0

[train.main]
seed = 0
trial_dir = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp/trial_00"
trained_model_dir = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp/trial_00/trained_model"
n_trained_model_dir_list = 99
dataset_path = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp/trial_00/trained_model/dataset_path.pkl"
batch_size = 1767
epoch = 8000
steps = 8000
change_val = "False"
init_lr = 0.0002288113668475521
anneal = "False"
anneal_method = ""
decay_rate = 0.0
weight_decay = 0.0
balance_loss_method = ""
diffusion_moving_average = "False"
log_start = 998
log_every = 2000
ema_every = 1

[train_mlp_params]
dim_in = 34
dim_t = 128
d_layers = [
    512,
    512,
    512,
    512,
    512,
    256,
]
dropout = 0.0

[train_diffusion_params]
n_timesteps = 1000
multinomial_loss_type = "vb_stochastic"
gaussian_loss_type = "mse"
gaussian_parametrization = "eps"
parametrization = "x0"
scheduler = "cosine"

[sample.main]
best_model_dir = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp/trial_00/trained_model/step_008000"
best_model_path = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp/trial_00/trained_model/step_008000/diffusion.pt"
seed = 14
sample_dir = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp/trial_00/sample_14"
n_sample_batches = 15
n_generate_times = 10
n_sample_times = 4
balance_sample_method = ""
smote_testset_only = ""
d_in_similarity = "/media/jie/toshiba_4t/7exp_t/tang/cvds/exp/trial_21/trained_model/step_1466/d_in_similarity.csv"
average_model_path = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp/trial_05/trained_model/step_1362/move_ave.pt"

[eval.main]
epoch_dir = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp/trial_00/sample_14/epochs_008000_random_generated/"
eval_dir = "/media/jie/toshiba_4t/7exp_t/tang/cvds_4_box_cox/exp/trial_00/eval/epochs_008000/sample_14"
seed = 14
shuffle_switch = "False"
